### ISSUE TITLE
Null Pointer Exception on Server

### ISSUE THREAD

**Issue by Aridastle** [ssblur/scriptor#17]
When new chunks are generating, this error will occasionally be thrown and will sometimes stall out/crash the server. Let me know if you need additional details.

[12.03 19:33:32] [Server] java.lang.NullPointerExceptionCannot read field "key" because "wordData" is null
[12.03 19:33:32] [Server] 	at TRANSFORMER/scriptor@0.2.11/com.ssblur.scriptor.helpers.DictionarySavedData.parse(DictionarySavedData.java:404)
[12.03 19:33:32] [Server] 	at TRANSFORMER/scriptor@0.2.11/com.ssblur.scriptor.events.SpellChatEvents.received(SpellChatEvents.java:23)
[12.03 19:33:32] [Server] 	at TRANSFORMER/architectury@6.4.62/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:160)
[12.03 19:33:32] [Server] 	at TRANSFORMER/architectury@6.4.62/dev.architectury.event.forge.__EventHandlerImplCommon_event_Submitted.invoke(.dynamic)
[12.03 19:33:32] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[12.03 19:33:32] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[12.03 19:33:32] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[12.03 19:33:32] [Server] 	at TRANSFORMER/forge@43.2.4/net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:463)
[12.03 19:33:32] [Server] 	at TRANSFORMER/forge@43.2.4/net.minecraftforge.common.ForgeHooks$1.lambda$decorate$0(ForgeHooks.java:476)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[12.03 19:33:32] [Server] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by ssblur** [comment]
Thank you for reporting. Can you update to version 0.2.12? That version should fix this issue.

**Comment by Aridastle** [comment]
Issue is still occurring in most recent 0.2.13 version:

[21.03 21:47:17] [Server] java.lang.NullPointerExceptionCannot read field "key" because "wordData" is null
[21.03 21:47:17] [Server] 	at TRANSFORMER/scriptor@0.2.13/com.ssblur.scriptor.helpers.DictionarySavedData.parse(DictionarySavedData.java:406)
[21.03 21:47:17] [Server] 	at TRANSFORMER/scriptor@0.2.13/com.ssblur.scriptor.events.SpellChatEvents.received(SpellChatEvents.java:23)
[21.03 21:47:17] [Server] 	at TRANSFORMER/architectury@6.5.69/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:160)
[21.03 21:47:17] [Server] 	at TRANSFORMER/architectury@6.5.69/dev.architectury.event.forge.__EventHandlerImplCommon_event_Submitted.invoke(.dynamic)
[21.03 21:47:17] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[21.03 21:47:17] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[21.03 21:47:17] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[21.03 21:47:17] [Server] 	at TRANSFORMER/forge@43.2.4/net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:463)
[21.03 21:47:17] [Server] 	at TRANSFORMER/forge@43.2.4/net.minecraftforge.common.ForgeHooks$1.lambda$decorate$0(ForgeHooks.java:476)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21.03 21:47:17] [Server] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by ssblur** [comment]
Building a version which circumvents this, but this error is likely not the cause of a crash. Messaged in DC, but can you attach a crash log or a full log? Thank you!

**Comment by Aridastle** [comment]
[RightBeforeError.log](https://github.com/ssblur/scriptor/files/11035249/RightBeforeError.log)
This is right before the error earlier occurred. Looks like the latest.log either doesn't see the error or isn't able to save it. The above ones I copy/pasted from console

**Comment by ssblur** [comment]
The error spit out by Scriptor appears to be incidental to this crash, so I'm closing this issue. Please feel free to reopen this issue if you have reason to believe the latest version is causing your server to crash.
